apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: postgresql
data:
  POSTGRES_DB: postgres

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: postgresql
data:
  POSTGRES_PASSWORD: <Desired Password in Base64>
  POSTGRES_USER: <Desired Username in Base64>

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: postgresql
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres  
    spec:
      containers:
      - name: postgres
        image: postgres:17-alpine3.21
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: POSTGRES_DB
        volumeMounts:
        - name: postgres-database-storage
          mountPath: /var/lib/pgsql/data
      volumes:
      - name: postgres-database-storage
        persistentVolumeClaim:
          claimName: postgres-pv-claim

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres


kubectl exec -it pods/postgres-statefulset-0 -n postgresql -- psql -U postgres -d postgres -h postgres-service
kubectl port-forward --address localhost,192.168.16.133 pods/postgres-statefulset-0 -n postgresql 5432:5432