- name: Playbook for AWS S3 Bucket
  hosts: localhost
  connection: local
  tasks:
    - name: Test Create S3 Bucket
      amazon.aws.s3_bucket:
        name: testbucket
        aws_access_key: test
        aws_secret_key: test
        region: us-east-1
        acl: private
        s3_url: http://s3.localhost.localstack.cloud:4566